version: '2.2'
services:
  registry:
    restart: always
    image: bl4ckbird/registry-arm64:latest
    ports:
      - 5030:5030
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5030
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /root/sec-registry/data:/var/lib/registry
      - /root/sec-registry/data/certs:/certs
      - /root/sec-registry/data/auth:/auth
